# The address to bind the server to.
address = "127.0.0.1"

# The port to bind the server to.
port = 8000

# The base path for the file storage.
file_base_path = "uploads"

# The base path for temporary files.
temp_base_path = "temp"

# The base URL for the database, without the database name.
# The database must be a PostgreSQL database.
# e.g. `postgres://user:password@localhost:5432`
database_url_base = "postgres://user:password@localhost:5432"

# The name of the database to use.
# The database must be exist and be empty.
database_name = "file_server"

# The URL for the MeiliSearch server.
meilisearch_url = "http://localhost:7700"

# The master key for the MeiliSearch server.
meilisearch_master_key = "master_key"

# The prefix for the MeiliSearch index. It will be lowercased.
# All indices created by the application will have this prefix.
meilisearch_index_prefix = "file_server"

# The period to remove expired staging files.
# The period is in seconds.
remove_expired_staging_files_period = 3600

# The expiration for staging files.
# The expiration is in seconds.
expired_staging_file_expiration = 86400

# The initial user to create.
# This initial user will be created when the application starts, if it does not exist.
[initial_user]
username = "username"
email = "username@example.com"
password = "password"

# The limits for the application.
[limits]
form = "32KiB"
data_form = "2MiB"
file = "1MiB"
string = "8KiB"
bytes = "8KiB"
json = "1MiB"
msgpack = "1MiB"
