
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: polytag

      RUST_CHANNEL: nightly

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        ports:
          - 5432:5432

      meilisearch:
        image: getmeili/meilisearch
        options: >-
          --health-cmd "wget -q localhost:7700/health -O /dev/null"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 7700:7700

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: |
        rustup update --no-self-update ${{ env.RUST_CHANNEL }}

    - name: Compile (tests)
      run: cargo test --no-run

    - name: Test
      run: cargo test
      env:
        FILE_BASE_PATH: temp/files
        TEMP_BASE_PATH: temp/temp

        DATABASE_URL_BASE: postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432
        DATABASE_NAME: ${{ env.POSTGRES_DB }}
        MAINTENANCE_DATABASE_NAME: postgres

        MEILISEARCH_URL: http://localhost:7700
